### ISSUE TITLE
Does not create schedule

### ISSUE THREAD

**Issue by db0** [redhataccess/ansible-redhat-access-insights-client#4]
I don't know why, but when I register the insight-client using the command line, it defaults to always include "--enable-schedule" by default (i.e. the schedules are installed). 

However if I install it via this ansible role, the schedule is not installed (even though the module effectively runs the same `insights-client --register` command)

**Comment by db0** [comment]
I think I've traced this bug. It's because the insights-client --status always returns exit code 0, even when the system it unregistered

**Comment by lphiri** [comment]
@db0  This is no longer maintained. Please use https://github.com/RedHatInsights/insights-client-role
