### ISSUE TITLE
replace yum for package module to support both yum (<=RHEL7) and dnf (RHEL8)

### ISSUE THREAD

**Issue by dciancio** [redhataccess/ansible-redhat-access-insights-client#5]
From my satellite 6.5 server, when trying to deploy ansible role (RedHatInsights.insights-client), I get the following error when deploying a RHEL8 client:

---
TASK [RedHatInsights.insights-client : Check for 'insights-client' RPM availability] ***
fatal: [rhel8client.mydomain.com]: FAILED! => {"changed": false, "msg": "The Python 2 yum module is needed for this module. If you require Python 3 support use the `dnf` Ansible module instead."}
---
Since python 2 is not installed on a RHEL8 system.  Can we have the playbook support dnf as well, in this case, specify 'package' module which would automatically pick the appropriate package manager.

Thanks!

**Comment by lphiri** [comment]
@dciancio this is no longer maintained.
Please use : https://github.com/RedHatInsights/insights-client-role which has a parameter for setting the python intepreter.
